development:
  clients:
    default:
      database: loyalty_db_dev
      hosts:
        - localhost:27017
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
      options:
        skip_version_check: true
        safe: true
